databases:
  - name: baims-db
    databaseName: baims
    user: baims_user

services:
  - type: web
    name: baims
    env: python
    # For stability, using a Long-Term Support (LTS) version of Python is recommended.
    pythonVersion: "3.12"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn baims.wsgi" # Corrected start command
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baims-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true # Automatically generates a secure secret key
      - key: WEB_CONCURRENCY
        value: 4
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.onrender.com,http://localhost:3000" # Example: replace with your actual frontend domain(s)
      - key: DEBUG
        value: "False" # Set DEBUG to False in production