# Generated by Django 5.0.6 on 2025-06-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('holding_table', models.TextField()),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='AirtelCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Airtel Combined Data',
                'verbose_name_plural': 'Airtel Combined Data',
                'db_table': 'airtel_combined',
            },
        ),
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'App Data',
                'verbose_name_plural': 'App Data',
                'db_table': 'app_data',
            },
        ),
        migrations.CreateModel(
            name='Ba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('company', models.IntegerField()),
                ('pass_code', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'BA',
                'verbose_name_plural': 'BAs',
                'db_table': 'ba',
            },
        ),
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Backend',
                'verbose_name_plural': 'Backends',
                'db_table': 'backend',
            },
        ),
        migrations.CreateModel(
            name='BaimsCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Baims Combined Data',
                'verbose_name_plural': 'Baims Combined Data',
                'db_table': 'baims_combined',
            },
        ),
        migrations.CreateModel(
            name='BaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'BA Project',
                'verbose_name_plural': 'BA Projects',
                'db_table': 'ba_project',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='CokeCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coke Combined Data',
                'verbose_name_plural': 'Coke Combined Data',
                'db_table': 'coke_combined',
            },
        ),
        migrations.CreateModel(
            name='ContainerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Container Option',
                'verbose_name_plural': 'Container Options',
                'db_table': 'container_options',
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'db_table': 'containers',
            },
        ),
        migrations.CreateModel(
            name='Coop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Coop',
                'verbose_name_plural': 'Coops',
                'db_table': 'coop',
            },
        ),
        migrations.CreateModel(
            name='Coop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Coop2',
                'verbose_name_plural': 'Coop2s',
                'db_table': 'coop2',
            },
        ),
        migrations.CreateModel(
            name='FormSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Form Sub Section',
                'verbose_name_plural': 'Form Sub Sections',
                'db_table': 'form_sub_section',
            },
        ),
        migrations.CreateModel(
            name='InputGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Input Group',
                'verbose_name_plural': 'Input Groups',
                'db_table': 'input_group',
            },
        ),
        migrations.CreateModel(
            name='InputOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('title', models.TextField()),
                ('rank', models.IntegerField()),
                ('next_section', models.IntegerField()),
                ('value', models.IntegerField()),
                ('container_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Input Option',
                'verbose_name_plural': 'Input Options',
                'db_table': 'input_options',
            },
        ),
        migrations.CreateModel(
            name='KspcaCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPSCA Combined Data',
                'verbose_name_plural': 'KPSCA Combined Data',
                'db_table': 'kspca_combined',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('t_date', models.DateField(blank=True, null=True)),
                ('t_time', models.TimeField(blank=True, null=True)),
                ('update_by', models.IntegerField(default=0)),
                ('photo', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('outlet_location', models.TextField(blank=True, null=True)),
                ('items_given', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('t_shirt', models.IntegerField(default=0)),
                ('money_bag', models.IntegerField(default=0)),
                ('table_mat', models.IntegerField(default=0)),
                ('parasol', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'db_table': 'outlet',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('client', models.TextField()),
                ('top_table', models.TextField()),
                ('rank', models.IntegerField()),
                ('combined', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('location_status', models.CharField(default='off', max_length=64)),
                ('company', models.IntegerField()),
                ('image_required', models.CharField(default='NO', max_length=64)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('report_display_name', models.TextField()),
                ('column_name', models.TextField()),
                ('rank', models.IntegerField()),
                ('field_type', models.CharField(max_length=128)),
                ('multiple', models.IntegerField()),
                ('options_available', models.IntegerField()),
                ('options_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Project Association',
                'verbose_name_plural': 'Project Associations',
                'db_table': 'project_assoc',
            },
        ),
        migrations.CreateModel(
            name='ProjectHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('company', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('aka_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Project Head',
                'verbose_name_plural': 'Project Heads',
                'db_table': 'project_head',
            },
        ),
        migrations.CreateModel(
            name='RedbullOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Redbull Outlet',
                'verbose_name_plural': 'Redbull Outlets',
                'db_table': 'redbull_outlet',
            },
        ),
        migrations.CreateModel(
            name='SaffCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Safaricom Combined Data',
                'verbose_name_plural': 'Safaricom Combined Data',
                'db_table': 'saff_combined',
            },
        ),
        migrations.CreateModel(
            name='TotalKenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Total Kenya Data',
                'verbose_name_plural': 'Total Kenya Data',
                'db_table': 'total_kenya',
            },
        ),
        migrations.CreateModel(
            name='UAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('u_name', models.TextField()),
                ('p_phrase', models.TextField()),
                ('powers', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'u_admin',
            },
        ),
        migrations.CreateModel(
            name='UserOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('outlet', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User Outlet',
                'verbose_name_plural': 'User Outlets',
                'db_table': 'user_outlet',
            },
        ),
        migrations.CreateModel(
            name='BaAuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='apis.ba', verbose_name='BA User')),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rank', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sections', to='apis.project')),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'db_table': 'form_section',
            },
        ),
        migrations.CreateModel(
            name='AdminAuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='apis.uadmin', verbose_name='Admin User')),
            ],
        ),
        migrations.CreateModel(
            name='UAdminAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='apis.agency')),
                ('uadmin', models.ForeignKey(db_column='uadmin_id', on_delete=django.db.models.deletion.CASCADE, to='apis.uadmin')),
            ],
            options={
                'db_table': 'u_admin_agencies',
                'unique_together': {('uadmin', 'agency')},
            },
        ),
        migrations.AddField(
            model_name='uadmin',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='admins', through='apis.UAdminAgency', to='apis.agency'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('active_status', models.IntegerField(default=1)),
                ('place_holder', models.IntegerField(default=0)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apis.agency')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='apis.user', verbose_name='User')),
            ],
        ),
    ]
