# Generated by Django 5.0.6 on 2025-06-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAdminAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.CASCADE, to='apis.agency')),
                ('uadmin', models.ForeignKey(db_column='uadmin_id', on_delete=django.db.models.deletion.CASCADE, to='apis.uadmin')),
            ],
            options={
                'db_table': 'u_admin_agencies',
                'unique_together': {('uadmin', 'agency')},
            },
        ),
        migrations.AddField(
            model_name='uadmin',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='admins', through='apis.UAdminAgency', to='apis.agency'),
        ),
    ]
