# Generated by Django 5.0.6 on 2025-06-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsection',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, related_name='form_sections', to='apis.project'),
        ),
    ]
