# Generated by Django 5.0.6 on 2025-06-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_formsection_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputoptions',
            name='next_section',
        ),
    ]
