# Generated by Django 5.0.6 on 2025-06-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_agency_airtelcombined_appdata_ba_backend_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE user
            ADD COLUMN agency_id INT,
            ADD CONSTRAINT fk_user_agency
            FOREIGN KEY (agency_id) REFERENCES agency(id);
            """,
            """
            ALTER TABLE user
            DROP FOREIGN KEY fk_user_agency,
            DROP COLUMN agency_id;
            """
        ),
    ]
