# Generated by Django 5.0.6 on 2025-06-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20250622_1803'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE user ENGINE=InnoDB",
            "ALTER TABLE user ENGINE=MyISAM"  # This is the reverse operation
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='apis.user', verbose_name='User')),
            ],
        ),
    ]
